version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: docker2001
      POSTGRES_PASSWORD: docker2001
      POSTGRES_DB: instock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: